// Auto-sync content sources before build.
// Reads ORCID, GitHub and Instagram, then writes src/data/auto/*.js
//
// Required secrets (configured as GitHub repository secrets or env vars):
//   ORCID_ID                    - e.g. 0000-0001-2345-6789
//   GITHUB_TOKEN                - optional, increases GitHub API rate limit
//   INSTAGRAM_TOKEN             - Instagram Basic Display long-lived token
//   INSTAGRAM_SESSION           - optional sessionid cookie fallback (not recommended)

import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '../src/data/auto');

const ORCID_ID = process.env.ORCID_ID || '';
const ORCID_AUTHOR_NAME = process.env.ORCID_AUTHOR_NAME || 'Immanuvel Prathap Sagayaraju';
const GITHUB_USERNAME = process.env.GITHUB_USERNAME || 'immanuvelprathap';
const GITHUB_TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || '';
const GITHUB_EXCLUDE = new Set(
  (process.env.GITHUB_EXCLUDE || 'immanuvelprathap,Portfolio')
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean)
);
const INSTAGRAM_TOKEN = process.env.INSTAGRAM_TOKEN || '';
const INSTAGRAM_USERNAME = process.env.INSTAGRAM_USERNAME || 'pahtarp_levunammi';
const INSTAGRAM_SESSION = process.env.INSTAGRAM_SESSION || '';

async function httpGetJson(url, options = {}) {
  const res = await fetch(url, options);
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`HTTP ${res.status} ${res.statusText} from ${url}: ${text.slice(0, 200)}`);
  }
  return res.json();
}

function toTitleCase(str) {
  return str
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function writeJs(name, data, meta = {}) {
  const filePath = resolve(OUT_DIR, `${name}.js`);
  const exists = existsSync(filePath);
  if (!data.length && exists) {
    console.log(`[sync] ${name}: no new data fetched; keeping existing file`);
    return;
  }
  const header = [
    '// Auto-generated by scripts/sync-content.js — do not edit manually.',
    `// generatedAt: ${new Date().toISOString()}`,
    meta.source ? `// source: ${meta.source}` : null,
  ]
    .filter(Boolean)
    .join('\n');
  const body = `export default ${JSON.stringify(data, null, 2)};`;
  return writeFile(filePath, `${header}\n${body}\n`);
}

async function syncGitHub() {
  const headers = {};
  if (GITHUB_TOKEN) headers.Authorization = `Bearer ${GITHUB_TOKEN}`;

  let repos = [];
  let page = 1;
  let fetched;
  do {
    const url = `https://api.github.com/users/${GITHUB_USERNAME}/repos?sort=pushed&direction=desc&per_page=100&page=${page}`;
    fetched = await httpGetJson(url, { headers });
    repos = repos.concat(fetched);
    page += 1;
  } while (fetched.length === 100 && page <= 5);

  const glyphMap = {
    Python: '\u2605',
    'Jupyter Notebook': '\u2605',
    JavaScript: '\u2600',
    TypeScript: '\u2600',
    HTML: '\u263D',
    CSS: '\u263D',
    Rust: '\u26A1',
    Go: '\u221E',
    Java: '\u2668',
    'C++': '\u2699',
    C: '\u2699',
    Shell: '\u2318',
  };

  const projects = repos
    .filter((r) => !r.fork && !GITHUB_EXCLUDE.has(r.name.toLowerCase()))
    .map((r) => {
      const branch = r.topics?.[0]
        ? toTitleCase(r.topics[0])
        : r.language || 'Open Source';
      const tags = r.topics?.length
        ? r.topics.slice(0, 4)
        : (r.language ? [r.language] : ['Code']);
      return {
        id: `gh-${r.id}`,
        name: toTitleCase(r.name),
        branch,
        glyph: glyphMap[r.language] || '\u2726',
        desc: r.description || `Source code for ${toTitleCase(r.name)}.`,
        tags,
        link: r.html_url,
        img: null,
      };
    });

  await writeJs('github', projects, { source: `github.com/${GITHUB_USERNAME}` });
  console.log(`[sync] github: ${projects.length} project(s)`);
}

async function syncOrcid() {
  if (!ORCID_ID) {
    console.log('[sync] orcid: ORCID_ID not set — skipping');
    await writeJs('orcid', []);
    return;
  }

  const url = `https://pub.orcid.org/v3.0/${ORCID_ID}/works`;
  const data = await httpGetJson(url, { headers: { Accept: 'application/json' } });
  const groups = data.group || [];

  const works = groups
    .map((g) => {
      const summary = g['work-summary']?.[0];
      if (!summary) return null;
      const title = summary.title?.title?.value || 'Untitled work';
      const year = summary['publication-date']?.year?.value || '';
      const venue =
        summary['journal-title']?.value ||
        summary['publisher']?.value ||
        'Publication';
      const type = summary.type || 'Work';
      const ids = summary['external-ids']?.['external-id'] || [];
      const doi = ids.find((id) => id['external-id-type'] === 'doi')?.['external-id-value'];
      const arxivId = ids.find((id) => id['external-id-type'] === 'arxiv')?.['external-id-value'];
      const urlValue = summary.url?.value || '';
      let link = null;
      if (urlValue) link = urlValue;
      else if (doi) link = `https://doi.org/${doi}`;
      else if (arxivId) link = `https://arxiv.org/abs/${arxivId}`;

      const putCode = summary['put-code'] || g['put-code'];
      return {
        id: `orcid-${putCode}`,
        year: year ? String(year) : 'n.d.',
        title,
        authors: ORCID_AUTHOR_NAME,
        venue,
        status: type,
        summary: `${type}${doi ? ` · DOI: ${doi}` : ''}${arxivId ? ` · arXiv: ${arxivId}` : ''}`,
        link,
      };
    })
    .filter(Boolean);

  await writeJs('orcid', works, { source: `orcid.org/${ORCID_ID}` });
  console.log(`[sync] orcid: ${works.length} work(s)`);
}

function instagramPostFromNode(node) {
  const captionEdges = node.edge_media_to_caption?.edges || [];
  const caption = captionEdges[0]?.node?.text || '';
  const firstLine = caption.split('\n')[0].trim();
  const title = firstLine || 'Post';
  const shortcode = node.shortcode;
  return {
    id: node.id,
    shortcode,
    permalink: `https://www.instagram.com/p/${shortcode}/`,
    caption,
    title,
    location: node.location?.name || '',
    mediaUrl: node.display_url,
    thumbnailUrl: node.thumbnail_src,
    isVideo: node.is_video,
    timestamp: node.taken_at_timestamp ? new Date(node.taken_at_timestamp * 1000).toISOString() : '',
    mediaType: node.is_video ? 'VIDEO' : 'IMAGE',
  };
}

async function syncInstagramPublic() {
  const cookieParts = ['ig_did=0; csrftoken=0'];
  if (INSTAGRAM_SESSION) {
    cookieParts.push(`sessionid=${INSTAGRAM_SESSION}`);
  }
  const url = `https://www.instagram.com/api/v1/users/web_profile_info/?username=${INSTAGRAM_USERNAME}`;
  const data = await httpGetJson(url, {
    headers: {
      'X-IG-App-ID': '936619743392459',
      Accept: 'application/json',
      Cookie: cookieParts.join('; '),
    },
  });
  const edges = data.data?.user?.edge_owner_to_timeline_media?.edges || [];
  return edges.map((e) => instagramPostFromNode(e.node));
}

async function syncInstagramBasicDisplay() {
  const fields = 'id,caption,media_type,media_url,permalink,thumbnail_url,timestamp,username';
  const url = `https://graph.instagram.com/me/media?fields=${fields}&limit=50&access_token=${INSTAGRAM_TOKEN}`;
  const data = await httpGetJson(url);
  const posts = (data.data || []).map((p) => {
    const shortcode = p.permalink?.match(/\/p\/([^/]+)/)?.[1] || p.id;
    const firstLine = (p.caption || 'Post').split('\n')[0].trim();
    return {
      id: p.id,
      shortcode,
      permalink: p.permalink,
      caption: p.caption || '',
      title: firstLine || 'Post',
      location: '',
      mediaUrl: p.media_url || p.thumbnail_url,
      thumbnailUrl: p.thumbnail_url || p.media_url,
      isVideo: p.media_type === 'VIDEO',
      timestamp: p.timestamp,
      mediaType: p.media_type,
    };
  });
  return posts;
}

async function syncInstagram() {
  let posts = [];
  if (INSTAGRAM_TOKEN) {
    try {
      posts = await syncInstagramBasicDisplay();
    } catch (err) {
      console.warn('[sync] instagram basic display failed:', err.message);
    }
  }
  if (!posts.length && INSTAGRAM_SESSION) {
    try {
      posts = await syncInstagramPublic();
    } catch (err) {
      console.warn('[sync] instagram public scrape failed:', err.message);
    }
  }
  if (!posts.length && existsSync(resolve(OUT_DIR, 'instagram.js'))) {
    console.log('[sync] instagram: no fetch succeeded; keeping existing cache');
    return;
  }
  await writeJs('instagram', posts, { source: `instagram.com/${INSTAGRAM_USERNAME}` });
  console.log(`[sync] instagram: ${posts.length} post(s)`);
}

await mkdir(OUT_DIR, { recursive: true });

try {
  await syncGitHub();
} catch (err) {
  console.error('[sync] github error:', err.message);
}

try {
  await syncOrcid();
} catch (err) {
  console.error('[sync] orcid error:', err.message);
}

try {
  await syncInstagram();
} catch (err) {
  console.error('[sync] instagram error:', err.message);
}
